"""Motor Controller Hardware Design — Passives Calculations"""
import math
from calculations.base import _nearest_e, E12


class PassivesMixin:
    """Mixin providing calculations for: input_capacitors, shunt_resistors, snubber."""

    # ═══════════════════════════════════════════════════════════════════
    def calc_input_capacitors(self) -> dict:
        self._current_module = "input_capacitors"
        i_dc    = 0 if self.v_bus == 0 else self.power / self.v_bus
        try:
            delta_v = float(self.ovr.get("delta_v_ripple", 2.0))
        except (TypeError, ValueError):
            delta_v = 2.0
        if delta_v <= 0:
            self.audit_log.append(f"[DC Bus] WARNING: Invalid ripple target ΔV={delta_v}V. Using 2.0V default.")
            delta_v = 2.0
        if "delta_v_ripple" not in self.ovr:
            self._log_hc("input_capacitors", "Ripple voltage target", f"{delta_v} V", "User-configurable override (default 2.0V)")
        fsw     = self.fsw

        # ── 1. Rigorous 3-Phase DC Link RMS Ripple ──
        # Phase inductance switching ripple is fundamentally negligible at the DC bus. 
        # The true DC link ripple is generated by the bulk chopping of the phase currents.
        # Uses exact Kolar analytical integration for 3-Phase SVPWM DC-Link RMS Current:
        M = self._dc("input.spwm_mod_index")
        pf = 0.85 # Standard motor power factor at load
        i_ph_rms = self.i_max / math.sqrt(2)
        
        # I_c_rms^2 = I_ph_rms^2 * 2M * [ sqrt(3)/(4pi) + cos^2(phi)*(sqrt(3)/pi - 9M/16) ]
        term1 = math.sqrt(3) / (4 * math.pi)
        term2 = (pf**2) * ((math.sqrt(3) / math.pi) - (9 * M / 16))
        # Ensure domain safety for unusual overrides
        inner_bracket = max(0.001, term1 + term2)
        i_in_rms_sq = (i_ph_rms**2) * 2 * M * inner_bracket
        i_ripple_rms = math.sqrt(i_in_rms_sq)
        
        ripple_method = f"3-Phase SVPWM Analytic (M={M}, cosΦ={pf})"
        self.audit_log.append(f"[DC Bus] Analytic SVPWM Ripple: I_ph_rms={i_ph_rms:.1f}A -> I_dc_rms={i_ripple_rms:.1f}A.")

        # ── Hf Network inputs (must load first for iteration) ──────────────────────────────────────────────
        def _flt(key, default):
            try: return float(self.ovr.get(key, default))
            except (TypeError, ValueError): return float(default)
        def _int(key, default):
            try: return int(float(self.ovr.get(key, default)))
            except (TypeError, ValueError): return int(default)

        film_qty       = _int("film_qty",           2)
        film_size_uf   = _flt("film_size_uf",       4.7)
        film_v_rating  = _int("film_v_rating_v",   100)
        film_z_mohm    = _flt("film_z_mohm",        5.0)

        mlcc_qty       = _int("mlcc_qty",            6)
        mlcc_size_nf   = _flt("mlcc_size_nf",      100.0)
        mlcc_z_mohm    = _flt("mlcc_z_mohm",         2.0)
        mlcc_v_rating  = _int("mlcc_v_rating_v",    50)

        bypass_qty     = _int("bypass_qty",          2)
        bypass_size_uf = _flt("bypass_size_uf",      4.7)

        esr_typ_mohm = self._dc("input.esr_per_cap")
        self._log_hc("input_capacitors", "Typical ESR per bulk cap", f"{esr_typ_mohm} mΩ", "Electrolytic ESR estimate for thermal calc", "input.esr_per_cap")

        # ── 2. Bulk Capacitance Sizing (Charge Displacement & Load Sharing) ──
        # Max charge extraction in one PWM cycle for 3-phase VSI is approximately (I_max / (4 * fsw))
        c_req_total_uf = (self.i_max / (4 * fsw * delta_v)) * 1e6
        
        # Deduct MLCC and Film static capacitance
        c_hf_uf = (film_qty * film_size_uf) + (mlcc_qty * mlcc_size_nf * 1e-3)
        c_req_uf = max(0.0, c_req_total_uf - c_hf_uf)

        # Standard electrolytic selection
        min_bulk = int(self._dc("input.min_bulk_count"))
        bulk_uf  = self._dc("input.bulk_cap_uf")
        
        # Hard limits
        # Using 1.94A per cap as a sane baseline for standard 100uF/100V low-ESR caps
        I_BULK_RIPPLE_LIMIT_A = 1.94  

        # ── 3. True Vector Impedance (Z) Splitting & Iterative Ripple Solver ──
        # Capacitors share current inversely to their absolute impedance Z = sqrt(ESR^2 + Xc^2)
        def _z_mag_true(esr_mohm, c_farads, qty):
            if qty <= 0 or c_farads <= 0: return 1e9
            esr_tot = (esr_mohm * 1e-3) / qty
            c_tot   = c_farads * qty
            xc      = 1.0 / (2 * math.pi * fsw * c_tot)
            return math.sqrt(esr_tot**2 + xc**2)

        Zmag_film = _z_mag_true(film_z_mohm, film_size_uf * 1e-6, film_qty)
        Zmag_mlcc = _z_mag_true(mlcc_z_mohm, mlcc_size_nf * 1e-9, mlcc_qty)

        # Start with enough bulk caps to satisfy the raw delta_V charge rules
        n_caps = max(min_bulk, math.ceil(c_req_uf / bulk_uf))
        
        I_bulk = 0
        I_film = 0
        I_mlcc = 0
        Zmag_bulk = 1e9
        Zmag_eq = 1e9
        
        # Iteratively inject bulk caps until they share the ripple current cleanly below thermal rupture limits
        while n_caps <= 100:
            Zmag_bulk = _z_mag_true(esr_typ_mohm, bulk_uf * 1e-6, n_caps)
            Ymag_total = (1/Zmag_bulk) + (1/Zmag_film) + (1/Zmag_mlcc)
            Zmag_eq = 1 / Ymag_total

            # Ohmic split of RMS ripple current based on exact vector admittances at switching frequency
            I_bulk = i_ripple_rms * (Zmag_eq / Zmag_bulk)
            I_film = i_ripple_rms * (Zmag_eq / Zmag_film)
            I_mlcc = i_ripple_rms * (Zmag_eq / Zmag_mlcc)
            
            i_rip_per_cap = I_bulk / n_caps if n_caps > 0 else 0
            
            # Sub-2A is safe for good electrolytic. If higher, loop and force another cap in parallel.
            if i_rip_per_cap <= I_BULK_RIPPLE_LIMIT_A:
                break
            n_caps += 1

        c_total  = (n_caps * bulk_uf) + c_hf_uf   # µF exactly coupled
        v_ripple_actual = (self.i_max / (4 * fsw * c_total * 1e-6))

        # ── 4. ESR Budgeting (Peak limits) ──
        # The voltage drops instantly due to ESR across the maximum current square block (I_max).
        esr_total_budget_mohm = 0 if self.i_max == 0 else (delta_v / self.i_max) * 1000
        esr_per_cap           = esr_total_budget_mohm * n_caps

        # Power dissipation is rigorously I^2 * ESR (not I^2 * Z!)
        # Only the ESR dissipates heat. Re-calculate pure parallel ESR paths.
        p_cap_total = (I_bulk**2) * ((esr_typ_mohm * 1e-3) / n_caps) if n_caps > 0 else 0
        p_per_cap   = 0 if n_caps == 0 else p_cap_total / n_caps
        mlcc_power_loss_w = (I_mlcc**2) * ((mlcc_z_mohm * 1e-3) / mlcc_qty) if mlcc_qty > 0 else 0
        
        # MLCC DC Bias Safety verification
        mlcc_safety_warning = "SAFE"
        if self.v_bus > (0.6 * mlcc_v_rating):
            mlcc_safety_warning = "DANGER: Severe DC-Bias Derating"

        mlcc_parallel_z_mohm = round((mlcc_z_mohm / mlcc_qty) if mlcc_qty > 0 else mlcc_z_mohm, 3)
        i_rip_per_cap = 0 if n_caps == 0 else I_bulk / n_caps

        # ── Bypass Capacitor Power Loss ──
        # Power lost charging C_bypass per switch cycle: P = fsw * num_fets * (0.5 * Q_g^2 / C_bypass)
        qg = self._get(self.mosfet, "MOSFET", "qg", 92e-9)
        c_bypass_total_f = bypass_size_uf * 1e-6 * bypass_qty
        p_bypass_w = 0.0
        if c_bypass_total_f > 0:
            p_bypass_w = fsw * self.num_fets * (0.5 * (qg**2) / c_bypass_total_f)

        self.audit_log.append(
            f"[DC Bus] Scalar AC impedance split at {fsw/1000:.0f}kHz: "
            f"I_bulk={I_bulk:.1f}A, I_film={I_film:.1f}A, I_mlcc={I_mlcc:.1f}A."
        )

        return {
            "i_dc_a":                    round(i_dc,               2),
            "i_ripple_rms_a":            round(i_ripple_rms,       2),
            "ripple_method":             ripple_method,
            "delta_v_target_v":          delta_v,
            "c_bulk_required_uf":        round(c_req_uf,           1),
            "n_bulk_caps":               n_caps,
            "c_per_bulk_cap_uf":         bulk_uf,
            "c_total_uf":                c_total,
            "v_ripple_actual_v":         round(v_ripple_actual,    4),
            "esr_budget_total_mohm":     round(esr_total_budget_mohm, 1),
            "esr_budget_per_cap_mohm":   round(esr_per_cap,        1),
            "i_ripple_per_cap_a":        round(i_rip_per_cap,      2),
            "cap_dissipation_w":         round(p_cap_total,        3),
            "cap_dissipation_per_cap_w": round(p_per_cap,          4),
            "c_film_uf":                 film_size_uf,
            "c_film_v_rating":           film_v_rating,
            "c_film_qty":                film_qty,
            "c_film_z_mohm":             film_z_mohm,
            "c_mlcc_nf":                 mlcc_size_nf,
            "c_mlcc_z_per_cap_mohm":     mlcc_z_mohm,
            "c_mlcc_parallel_z_mohm":    mlcc_parallel_z_mohm,
            "c_mlcc_power_loss_w":       round(mlcc_power_loss_w,  4),
            "c_mlcc_v_rating":           mlcc_v_rating,
            "c_mlcc_qty":                mlcc_qty,
            "c_mlcc_safety_warning":     mlcc_safety_warning,
            "c_bypass_qty":              bypass_qty,
            "c_bypass_size_uf":          bypass_size_uf,
            "c_bypass_power_w":          round(p_bypass_w,         4),
            "c_mlcc_dielectric":         "X7R",
            "recommended_bulk_part":     f"Panasonic EEU-FC2A101 ({bulk_uf:.0f}µF, 1.94A ripple)",
            "notes": {
                "placement_bulk":  "Within 30mm of H-bridge, low-impedance bus bar",
                "placement_film":  "Within 20mm of each half-bridge section",
                "placement_mlcc":  "One per MOSFET switch node, as close as possible",
                "polarity":        "Electrolytic — verify polarity before power-on",
            },
            "_meta": self._module_meta.get("input_capacitors", {"hardcoded": [], "fallbacks": []}),
        }

    # ═══════════════════════════════════════════════════════════════════
    # 4. Bootstrap Capacitor
    # ═══════════════════════════════════════════════════════════════════

    # ═══════════════════════════════════════════════════════════════════
    def calc_shunt_resistors(self) -> dict:
        self._current_module = "shunt_resistors"
        i_max    = self.i_max

        # ── Topology selection ─────────────────────────────────────────────
        topology = str(self.ovr.get("shunt_topology", "three_phase")).strip().lower()
        if topology not in ("single", "three_phase"):
            topology = "three_phase"
        self.audit_log.append(f"[Current Sensing] Topology: {topology}.")

        # ── CSA gain ────────────────────────────────────────────────────────
        csa_gain_ds = self._get(self.driver, "DRIVER", "current_sense_gain", None)
        csa_gain_override_raw = self.ovr.get("csa_gain_override")
        if csa_gain_override_raw is not None:
            try:
                csa_gain = float(csa_gain_override_raw)
                self.audit_log.append(f"[Current Sensing] CSA gain manually overridden to {csa_gain}.")
            except (TypeError, ValueError):
                csa_gain = csa_gain_ds if (csa_gain_ds and csa_gain_ds > 0) else 20
        else:
            csa_gain = csa_gain_ds if (csa_gain_ds and csa_gain_ds > 0) else 20

        # ── ADC reference ───────────────────────────────────────────────────
        adc_ref_from_mcu = self._get(self.mcu, "MCU", "adc_ref", None)
        if adc_ref_from_mcu is not None and adc_ref_from_mcu > 0:
            adc_ref = adc_ref_from_mcu
            self.audit_log.append(f"[Current Sensing] Using ADC reference {adc_ref}V from MCU datasheet.")
        else:
            adc_ref = self._dc("prot.adc_ref")
            self._log_hc("shunt_resistors", "ADC reference", f"{adc_ref} V", "MCU ADC reference voltage (default)", "prot.adc_ref")

        adc_bits = self._get(self.mcu, "MCU", "adc_resolution", 12) or 12
        lsb_mv   = (adc_ref * 1000) / (2 ** int(adc_bits))

        def _mohm_ovr(key, default_val):
            try:
                v = float(self.ovr.get(key, default_val))
                return v if v > 0 else float(default_val)
            except (TypeError, ValueError):
                return float(default_val)

        # ── SINGLE SHUNT ────────────────────────────────────────────────────
        if topology == "single":
            # Bidirectional sensing: target 50% ADC ref so ±Imax maps to 0..Vref
            v_adc_max_limit = adc_ref * 0.5
            self._log_hc("shunt_resistors", "ADC limit (bidirectional)",
                         f"{v_adc_max_limit} V", "50% of ADC ref — maximum allowable swing before clipping")
            r_ideal_mohm = (v_adc_max_limit / (i_max * csa_gain)) * 1000
            r1_mohm_auto = 0.5 if r_ideal_mohm <= 0.75 else 1.0
            r1_mohm = _mohm_ovr("shunt_single_mohm", r1_mohm_auto)
            if "shunt_single_mohm" not in self.ovr:
                self._log_hc("shunt_resistors", "Single shunt auto-select", f"{r1_mohm} mOhm",
                             "Snapped to 0.5 or 1.0 mOhm standard value")
            
            i_peak_sine = i_max * math.sqrt(2)
            v_sh_mv  = i_max * r1_mohm * 1e-3 * 1000
            v_adc    = v_sh_mv * 1e-3 * csa_gain
            
            # ADC Swing calculation strictly honoring Peak Sinusoidal Current
            v_adc_swing_peak = (i_peak_sine * r1_mohm * 1e-3) * csa_gain
            
            p_dc_w   = i_max**2 * r1_mohm * 1e-3
            p_rms_w  = (i_max / math.sqrt(2))**2 * r1_mohm * 1e-3
            bits_used = math.log2(v_adc * 1000 / lsb_mv) if v_adc > 0 else 0
            active = {
                "topology":       "single",
                "quantity":       1,
                "location":       "DC bus low-side return (between GND and bottom FETs)",
                "value_mohm":     r1_mohm,
                "v_shunt_mv":       round(v_sh_mv,  2),
                "v_adc_v":          round(v_adc,    3),
                "v_adc_max_limit":  round(v_adc_max_limit, 3),
                "v_adc_swing_peak": round(v_adc_swing_peak, 3),
                "i_peak_sine_a":    round(i_peak_sine, 1),
                "adc_utilisation_pct": round(v_adc / adc_ref * 100, 1),
                "adc_bits_used":  round(bits_used, 1),
                "power_dc_w":     round(p_dc_w,   3),
                "power_rms_w":    round(p_rms_w,  3),
                "total_power_w":  round(p_dc_w,   3),
                "recommended":    "Isabellenhutte PMR / Vishay WSL 4-terminal Kelvin, 0.5 or 1 mOhm",
                "note":           "Single shunt requires ADC sample timing synchronised to PWM cycle.",
            }

        # ── THREE-PHASE SHUNTS ──────────────────────────────────────────────
        else:
            # Bidirectional Phase sensing: target 50% ADC ref so ±Ipeak maps perfectly without clipping
            v_adc_max_limit = adc_ref * 0.5
            self._log_hc("shunt_resistors", "ADC limit (bidirectional)",
                         f"{v_adc_max_limit} V", "50% of ADC ref - critical bidirectional swing limit")
            r_ideal_mohm = (v_adc_max_limit / (i_max * csa_gain)) * 1000
            r3_mohm_auto = 0.5 if r_ideal_mohm <= 0.75 else 1.0
            r3_mohm = _mohm_ovr("shunt_three_mohm", r3_mohm_auto)
            if "shunt_three_mohm" not in self.ovr:
                self._log_hc("shunt_resistors", "3-phase shunt auto-select", f"{r3_mohm} mOhm",
                             "Snapped to 0.5 or 1.0 mOhm standard value")
            
            i_peak_sine = i_max * math.sqrt(2)
            v_sh_mv  = i_max * r3_mohm * 1e-3 * 1000
            v_adc    = v_sh_mv * 1e-3 * csa_gain
            
            # ADC Swing calculation strictly honoring Peak Sinusoidal Current
            v_adc_swing_peak = (i_peak_sine * r3_mohm * 1e-3) * csa_gain
            
            p_rms_ea = (i_max / math.sqrt(2))**2 * r3_mohm * 1e-3
            bits_used = math.log2(v_adc * 1000 / lsb_mv) if v_adc > 0 else 0
            active = {
                "topology":       "three_phase",
                "quantity":       3,
                "location":       "Each phase low-side MOSFET source return (U, V, W)",
                "value_mohm":     r3_mohm,
                "v_shunt_mv":       round(v_sh_mv,  2),
                "v_adc_v":          round(v_adc,    3),
                "v_adc_max_limit":  round(v_adc_max_limit, 3),
                "v_adc_swing_peak": round(v_adc_swing_peak, 3),
                "i_peak_sine_a":    round(i_peak_sine, 1),
                "adc_utilisation_pct": round(v_adc / adc_ref * 100, 1),
                "adc_bits_used":  round(bits_used, 1),
                "power_rms_per_shunt_w": round(p_rms_ea, 3),
                "total_power_w":  round(p_rms_ea * 3, 3),
                "recommended":    "Isabellenhutte PMR 0.5 mOhm x3, Kelvin 4-terminal",
                "note":           "3-phase topology allows simultaneous phase current sampling. Best for FOC.",
            }

        return {
            "topology_mode":   topology,
            "csa_gain":        csa_gain,
            "csa_gain_source": "manual_override" if csa_gain_override_raw is not None
                               else ("datasheet" if csa_gain_ds else "default"),
            "adc_reference_v": adc_ref,
            "ideal_r_mohm":    round(r_ideal_mohm, 3),
            "active":          active,
            # Legacy keys kept for backward compatibility
            "single_shunt":    active if topology == "single" else {
                                   "value_mohm": None, "v_shunt_mv": None,
                                   "v_adc_v": None, "power_dc_w": None, "power_rms_w": None},
            "three_shunt":     active if topology == "three_phase" else {
                                   "value_mohm": None, "v_shunt_mv": None,
                                   "v_adc_v": None, "total_3_shunt_power_w": None},
            "notes": {
                "kelvin":    "MANDATORY 4-wire Kelvin sensing — sense traces inside power traces",
                "tc":        "Use <50 ppm/C temperature coefficient shunt",
                "tolerance": "+/-1% or better for accurate FOC",
                "topology":  "Populate EITHER single shunt OR 3-phase shunts — never both simultaneously",
            },
            "_meta": self._module_meta.get("shunt_resistors", {"hardcoded": [], "fallbacks": []}),
        }

    # ═══════════════════════════════════════════════════════════════════
    # 6. RC Snubber (Drain-Source)
    # ═══════════════════════════════════════════════════════════════════

    # ═══════════════════════════════════════════════════════════════════
    def calc_snubber(self) -> dict:
        self._current_module = "snubber"
        # Parasitic PCB trace inductance (target <5nH, assume 10nH worst case)
        try:
            l_stray_nh = float(self.ovr.get("stray_inductance_nh", 10.0))
        except (TypeError, ValueError):
            l_stray_nh = 10.0
        l_stray     = l_stray_nh * 1e-9

        # _get returns SI value (Farads if unit is pF/nF/etc), fallback is raw value.
        # fallback 200e-12 = 200pF in SI (Farads)
        coss = self._get(self.mosfet, "MOSFET", "coss", 200e-12)   # Farads (SI)
        coss_pf = coss * 1e12  # convert back to pF for display and E12 snapping

        # Resonant frequency of stray L and Coss
        # f_res = 1 / (2π√(L×C))
        if l_stray > 0 and coss > 0:
            f_res_mhz = 1.0 / (2 * math.pi * math.sqrt(l_stray * coss)) / 1e6
        else:
            f_res_mhz = 50.0

        # Voltage overshoot: V_ov = I × sqrt(L/C)
        v_overshoot = self.i_max * math.sqrt(l_stray / max(coss, 1e-15))
        v_sw_peak   = self.v_peak + v_overshoot

        # Snubber capacitor sizing: Cs ≈ N × Coss (read multiplier once)
        coss_mult = int(self._dc("snub.coss_mult"))
        self._log_hc("snubber", "Snubber cap formula", f"{coss_mult}× Coss", "Overdamped RC snubber design rule", "snub.coss_mult")
        self._log_hc("snubber", "Rs practical limits", "1–100 Ω", "Physical resistor sizing constraints")
        cs_pf_raw = coss_pf * coss_mult if coss_pf > 0 else 1000.0
        cs_pf_std = _nearest_e(cs_pf_raw, E12)
        cs_pf_std = max(100.0, cs_pf_std)

        # Snubber resistor: Rs = sqrt(L_stray / Cs_snubber)
        # This damps the Cs–L_stray loop (overdamped relative to the natural
        # Coss–L resonance because Cs > Coss).
        cs_for_rs   = max(cs_pf_std * 1e-12, 1e-15)
        rs_crit     = math.sqrt(l_stray / cs_for_rs)
        rs_std      = _nearest_e(rs_crit)

        # Log the stray inductance hardcode
        if l_stray_nh == 10.0:
            self.audit_log.append("[Snubber] Stray layout inductance not specified. Assumed 10nH default.")
        self.audit_log.append(
            f"[Snubber] Rs = √(L_stray / Cs) = √({l_stray_nh}nH / {cs_pf_std:.0f}pF) "
            f"= {rs_crit:.2f}Ω → overdamped relative to natural Coss–L resonance."
        )
        if rs_std < 1.0: rs_std = 1.0    # practical minimum
        if rs_std > 100: rs_std = 100.0  # practical maximum

        # ── Snubber value overrides ──────────────────────────────────────────────
        snub_rs_raw  = self.ovr.get("snubber_rs_ohm")
        snub_cs_raw  = self.ovr.get("snubber_cs_pf")
        snub_v_mult  = 2.0
        try: snub_v_mult = float(self.ovr.get("snubber_v_mult", 2.0))
        except (TypeError, ValueError): pass

        manual_snubber = False
        try:
            rs_man = float(snub_rs_raw)
            cs_man = float(snub_cs_raw)
            if rs_man > 0 and cs_man > 0:
                rs_recommend = rs_man
                cs_recommend = cs_man
                manual_snubber = True
                self.audit_log.append(
                    f"[Snubber] Manual override: Rs={rs_man}Ω, Cs={cs_man:.0f}pF entered by user."
                )
        except (TypeError, ValueError):
            pass

        if not manual_snubber:
            rs_recommend = max(1.0, min(100.0, round(rs_std, 0)))
            cs_recommend = cs_pf_std

        # ── Snubber response time check: 3τ must be < 0.5/fsw ──────────────────
        # The RC time constant τ = Rs × Cs must settle within the half-period so
        # the snubber cap is discharged before the next switching event recharges it.
        # If 3τ ≥ 0.5/fsw the snubber cannot reset each cycle → energy accumulates.
        tau_snub = rs_recommend * (cs_recommend * 1e-12)
        half_period_s = 0.5 / self.fsw
        snubber_too_slow = (3 * tau_snub) >= half_period_s
        snubber_response_warning = None
        if snubber_too_slow:
            snubber_response_warning = (
                f"⚠ Snubber too slow: 3τ = {3*tau_snub*1e9:.0f} ns ≥ T/2 = {half_period_s*1e9:.0f} ns "
                f"(fsw = {self.fsw/1e3:.0f} kHz). Snubber cap cannot reset each cycle. "
                f"Reduce Rs ({rs_recommend:.0f}→{rs_recommend*0.5:.0f}Ω) or Cs ({cs_recommend:.0f}→{cs_recommend/2:.0f}pF)."
            )
            self.audit_log.append(f"[Snubber] WARNING: {snubber_response_warning}")
        else:
            self.audit_log.append(
                f"[Snubber] Response check OK: 3τ = {3*tau_snub*1e9:.0f} ns < T/2 = {half_period_s*1e9:.0f} ns."
            )

        # Cap V-rating must withstand V_peak PLUS the overshoot transient
        cap_v_rating = int((self.v_peak + v_overshoot) * snub_v_mult)
        # Dynamic snubber cap label
        if cs_recommend >= 1000:
            cs_label = f"{cs_recommend/1000:.0f}nF / {cap_v_rating}V X7R MLCC"
        else:
            cs_label = f"{cs_recommend:.0f}pF / {cap_v_rating}V X7R MLCC"

        # Snubber power dissipation (per MOSFET)
        # The capacitor charges to v_sw_peak = V_peak + V_overshoot each cycle,
        # then dumps that energy into Rs.  P = ½ × Cs × V_sw_peak² × fsw.
        p_snubber = 0.5 * (cs_recommend * 1e-12) * (v_sw_peak**2) * self.fsw
        p_snubber_total = p_snubber * self.num_fets

        # Qoss energy validation — compare snubber energy with Coss stored energy
        qoss = self._get(self.mosfet, "MOSFET", "qoss", None)  # C (SI)
        qoss_info = {}
        if qoss is not None:
            e_oss_uj  = qoss * self.v_peak / 2 * 1e6  # µJ
            e_snub_uj = 0.5 * (cs_recommend * 1e-12) * (self.v_peak ** 2) * 1e6  # µJ
            qoss_info = {
                "qoss_nC":              round(qoss * 1e9, 0),
                "e_oss_uj":             round(e_oss_uj, 2),
                "e_snubber_uj":         round(e_snub_uj, 2),
                "snubber_absorbs_oss":  e_snub_uj >= e_oss_uj,
            }
            self.audit_log.append(f"[Snubber] Qoss={qoss*1e9:.0f}nC from datasheet. E_oss={e_oss_uj:.1f}µJ, E_snub={e_snub_uj:.1f}µJ.")

        result = {
            "num_fets":                   self.num_fets,
            "stray_inductance_nh":        l_stray_nh,
            "coss_pf":                    coss_pf,
            "resonant_freq_mhz":          round(f_res_mhz,    1),
            "voltage_overshoot_v":        round(v_overshoot,   1),
            "v_sw_peak_v":                round(v_sw_peak,     1),
            "rs_critical_ohm":            round(rs_crit,       2),
            "rs_recommended_ohm":         rs_recommend,
            "cs_recommended_pf":          cs_recommend,
            "cs_recommended_label":       cs_label,
            "snubber_cap_v_rating":       cap_v_rating,
            "manual_snubber_values":      manual_snubber,
            "p_per_snubber_w":            round(p_snubber,     4),
            "p_total_all_snubbers_w":     round(p_snubber_total, 3),
            "p_total_6_snubbers_w":       round(p_snubber_total, 3),  # backward compat
            "rs_power_rating":            "0.1W minimum (0402)",
            "snubber_tau_ns":             round(tau_snub * 1e9, 1),
            "snubber_3tau_ns":            round(3 * tau_snub * 1e9, 1),
            "half_period_ns":             round(half_period_s * 1e9, 1),
            "snubber_too_slow":           snubber_too_slow,
            "snubber_response_warning":   snubber_response_warning,
            "notes": {
                "rs_placement":   "Place Cs physically closest to MOSFET D-S pins",
                "v_rating":       f"Snubber cap voltage rating: {cap_v_rating}V minimum ({snub_v_mult:.1f}×(Vpeak+Vovershoot))",
                "reduce_stray":   "Reducing PCB stray inductance is more effective than snubbers",
                "pcb_technique":  "Use mirrored top/bottom copper pours for low-inductance half-bridge",
            },
            "_meta": self._module_meta.get("snubber", {"hardcoded": [], "fallbacks": []}),
        }
        if qoss_info:
            result["qoss_validation"] = qoss_info

        return result

    # ═══════════════════════════════════════════════════════════════════
    # 7. Protection Voltage Dividers
    # ═══════════════════════════════════════════════════════════════════

